# generated by datamodel-codegen:
#   filename:  dip.schema.json

from __future__ import annotations

from dataclasses import dataclass
from enum import StrEnum
from typing import List, Literal, Optional


@dataclass
class DIP:
    pass


@dataclass
class Prologue:
    control_len: int
    payload_len: int
    protocol: Optional[int] = None


class ErrorCode(StrEnum):
    bad_request = 'bad_request'
    unknown_model = 'unknown_model'
    unsupported_engine = 'unsupported_engine'
    checksum_mismatch = 'checksum_mismatch'
    fetch_failed = 'fetch_failed'
    no_model_loaded = 'no_model_loaded'
    timeout = 'timeout'
    busy = 'busy'
    response_too_large = 'response_too_large'
    internal = 'internal'


@dataclass
class ErrorBody:
    code: ErrorCode
    message: str


@dataclass
class ErrorResponse:
    ok: Literal[False]
    error: ErrorBody


@dataclass
class Limits:
    max_chunk: int
    max_control: int
    max_payload: int
    idle_timeout_s: int
    message_timeout_s: int


@dataclass
class Resident:
    id: str
    engine: str
    langs: List[str]
    resident_seconds: float


class Op(StrEnum):
    handshake = 'handshake'
    version = 'version'


@dataclass
class HandshakeRequest:
    op: Op


@dataclass
class HandshakeResponse:
    ok: Literal[True]
    service: str
    version: str
    protocol: int
    limits: Limits
    engines: List[str]
    ops: List[str]
    default_model: str
    resident: Optional[Resident] = None
    loading: Optional[str] = None


@dataclass
class ListRequest:
    op: Literal['list']


class SourceType(StrEnum):
    huggingface = 'huggingface'
    system = 'system'


@dataclass
class ModelSummary:
    id: str
    description: str
    engine: str
    langs: List[str]
    source_type: SourceType
    files: int
    bytes: int
    unverified_files: List[str]


@dataclass
class ListResponse:
    ok: Literal[True]
    models: List[ModelSummary]
    default_model: str
    resident: Optional[Resident] = None
    loading: Optional[str] = None


@dataclass
class LoadRequest:
    op: Literal['load']
    id: Optional[str] = None
    model: Optional[str] = None


@dataclass
class LoadResponse:
    ok: Literal[True]
    id: str
    engine: str
    already_resident: bool
    load_ms: float
    unloaded: Optional[str]


@dataclass
class UnloadRequest:
    op: Literal['unload']


@dataclass
class UnloadResponse:
    ok: Literal[True]
    unloaded: Optional[str]


@dataclass
class InferRequest:
    op: Literal['infer']


class Op1(StrEnum):
    livez = 'livez'
    readyz = 'readyz'
    startupz = 'startupz'


@dataclass
class ProbeRequest:
    op: Op1


class Probe(StrEnum):
    livez = 'livez'
    readyz = 'readyz'
    startupz = 'startupz'


class Status(StrEnum):
    pass_ = 'pass'
    fail = 'fail'


@dataclass
class ProbeResponse:
    ok: bool
    probe: Probe
    status: Status
    uptime_s: float
    reasons: List[str]
    resident: Optional[Resident] = None
    loading: Optional[str] = None


type Point = List[float]


@dataclass
class Line:
    text: str
    confidence: Optional[float]
    box: Optional[List[Point]]


@dataclass
class InferResponse:
    ok: Literal[True]
    text: str
    lines: List[Line]
    model: str
    infer_ms: float
