// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package dip

import "encoding/json"
import "fmt"
import "reflect"

type ErrorBody struct {
	Code ErrorCode `json:"code"`

	// Prose for humans and logs. Not a contract.
	Message string `json:"message"`
}

func (j *ErrorBody) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["code"]; raw != nil && !ok {
		return fmt.Errorf("field code in ErrorBody: required")
	}
	if _, ok := raw["message"]; raw != nil && !ok {
		return fmt.Errorf("field message in ErrorBody: required")
	}
	type Plain ErrorBody
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = ErrorBody(plain)
	return nil
}

type ErrorCode string

const ErrorCodeBadRequest ErrorCode = "bad_request"
const ErrorCodeBusy ErrorCode = "busy"
const ErrorCodeChecksumMismatch ErrorCode = "checksum_mismatch"
const ErrorCodeFetchFailed ErrorCode = "fetch_failed"
const ErrorCodeInternal ErrorCode = "internal"
const ErrorCodeNoModelLoaded ErrorCode = "no_model_loaded"
const ErrorCodeResponseTooLarge ErrorCode = "response_too_large"
const ErrorCodeTimeout ErrorCode = "timeout"
const ErrorCodeUnknownModel ErrorCode = "unknown_model"
const ErrorCodeUnsupportedEngine ErrorCode = "unsupported_engine"

var enumValues_ErrorCode = []interface{}{
	"bad_request",
	"unknown_model",
	"unsupported_engine",
	"checksum_mismatch",
	"fetch_failed",
	"no_model_loaded",
	"timeout",
	"busy",
	"response_too_large",
	"internal",
}

func (j *ErrorCode) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_ErrorCode {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_ErrorCode, v)
	}
	*j = ErrorCode(v)
	return nil
}

type ErrorResponse struct {
	Error ErrorBody `json:"error"`

	Ok bool `json:"ok"`
}

func (j *ErrorResponse) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["error"]; raw != nil && !ok {
		return fmt.Errorf("field error in ErrorResponse: required")
	}
	if _, ok := raw["ok"]; raw != nil && !ok {
		return fmt.Errorf("field ok in ErrorResponse: required")
	}
	type Plain ErrorResponse
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = ErrorResponse(plain)
	return nil
}

type HandshakeRequest struct {
	Op HandshakeRequestOp `json:"op"`
}

type HandshakeRequestOp string

const HandshakeRequestOpHandshake HandshakeRequestOp = "handshake"
const HandshakeRequestOpVersion HandshakeRequestOp = "version"

var enumValues_HandshakeRequestOp = []interface{}{
	"handshake",
	"version",
}

func (j *HandshakeRequestOp) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_HandshakeRequestOp {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_HandshakeRequestOp, v)
	}
	*j = HandshakeRequestOp(v)
	return nil
}

func (j *HandshakeRequest) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["op"]; raw != nil && !ok {
		return fmt.Errorf("field op in HandshakeRequest: required")
	}
	type Plain HandshakeRequest
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = HandshakeRequest(plain)
	return nil
}

type HandshakeResponse struct {
	DefaultModel string `json:"default_model"`

	Engines []string `json:"engines"`

	Limits Limits `json:"limits"`

	// Model being fetched, if any.
	Loading *string `json:"loading,omitempty"`

	Ok bool `json:"ok"`

	Ops []string `json:"ops"`

	// Wire version the peer speaks.
	Protocol int `json:"protocol"`

	Resident interface{} `json:"resident,omitempty"`

	Service string `json:"service"`

	// Implementation version, not the wire version.
	Version string `json:"version"`
}

func (j *HandshakeResponse) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["default_model"]; raw != nil && !ok {
		return fmt.Errorf("field default_model in HandshakeResponse: required")
	}
	if _, ok := raw["engines"]; raw != nil && !ok {
		return fmt.Errorf("field engines in HandshakeResponse: required")
	}
	if _, ok := raw["limits"]; raw != nil && !ok {
		return fmt.Errorf("field limits in HandshakeResponse: required")
	}
	if _, ok := raw["ok"]; raw != nil && !ok {
		return fmt.Errorf("field ok in HandshakeResponse: required")
	}
	if _, ok := raw["ops"]; raw != nil && !ok {
		return fmt.Errorf("field ops in HandshakeResponse: required")
	}
	if _, ok := raw["protocol"]; raw != nil && !ok {
		return fmt.Errorf("field protocol in HandshakeResponse: required")
	}
	if _, ok := raw["service"]; raw != nil && !ok {
		return fmt.Errorf("field service in HandshakeResponse: required")
	}
	if _, ok := raw["version"]; raw != nil && !ok {
		return fmt.Errorf("field version in HandshakeResponse: required")
	}
	type Plain HandshakeResponse
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = HandshakeResponse(plain)
	return nil
}

// Takes no model field. Load first, unload after, so which model answered is never
// in doubt. The image rides in the payload, not here.
type InferRequest struct {
	Op string `json:"op"`
}

func (j *InferRequest) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["op"]; raw != nil && !ok {
		return fmt.Errorf("field op in InferRequest: required")
	}
	type Plain InferRequest
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = InferRequest(plain)
	return nil
}

type InferResponse struct {
	InferMs float64 `json:"infer_ms"`

	Lines []Line `json:"lines"`

	// Which model actually answered.
	Model string `json:"model"`

	Ok bool `json:"ok"`

	// The lines joined with newlines.
	Text string `json:"text"`
}

func (j *InferResponse) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["infer_ms"]; raw != nil && !ok {
		return fmt.Errorf("field infer_ms in InferResponse: required")
	}
	if _, ok := raw["lines"]; raw != nil && !ok {
		return fmt.Errorf("field lines in InferResponse: required")
	}
	if _, ok := raw["model"]; raw != nil && !ok {
		return fmt.Errorf("field model in InferResponse: required")
	}
	if _, ok := raw["ok"]; raw != nil && !ok {
		return fmt.Errorf("field ok in InferResponse: required")
	}
	if _, ok := raw["text"]; raw != nil && !ok {
		return fmt.Errorf("field text in InferResponse: required")
	}
	type Plain InferResponse
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = InferResponse(plain)
	return nil
}

// Everything a peer needs to frame correctly. Advertised by handshake so nothing
// is hard-coded.
type Limits struct {
	// How long an open connection may sit between messages.
	IdleTimeoutS int `json:"idle_timeout_s"`

	// Largest datagram either side may send.
	MaxChunk int `json:"max_chunk"`

	// Largest control block.
	MaxControl int `json:"max_control"`

	// Largest payload.
	MaxPayload int `json:"max_payload"`

	// How long a half-sent message may stall.
	MessageTimeoutS int `json:"message_timeout_s"`
}

func (j *Limits) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["idle_timeout_s"]; raw != nil && !ok {
		return fmt.Errorf("field idle_timeout_s in Limits: required")
	}
	if _, ok := raw["max_chunk"]; raw != nil && !ok {
		return fmt.Errorf("field max_chunk in Limits: required")
	}
	if _, ok := raw["max_control"]; raw != nil && !ok {
		return fmt.Errorf("field max_control in Limits: required")
	}
	if _, ok := raw["max_payload"]; raw != nil && !ok {
		return fmt.Errorf("field max_payload in Limits: required")
	}
	if _, ok := raw["message_timeout_s"]; raw != nil && !ok {
		return fmt.Errorf("field message_timeout_s in Limits: required")
	}
	type Plain Limits
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = Limits(plain)
	return nil
}

type Line struct {
	// Four corners, clockwise from top-left. Null for engines that do not localise
	// text.
	Box []Point `json:"box"`

	// 0..1, or null when the engine does not report one.
	Confidence *float64 `json:"confidence"`

	Text string `json:"text"`
}

func (j *Line) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["box"]; raw != nil && !ok {
		return fmt.Errorf("field box in Line: required")
	}
	if _, ok := raw["confidence"]; raw != nil && !ok {
		return fmt.Errorf("field confidence in Line: required")
	}
	if _, ok := raw["text"]; raw != nil && !ok {
		return fmt.Errorf("field text in Line: required")
	}
	type Plain Line
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.Box != nil && len(plain.Box) < 4 {
		return fmt.Errorf("field %s length: must be >= %d", "box", 4)
	}
	if len(plain.Box) > 4 {
		return fmt.Errorf("field %s length: must be <= %d", "box", 4)
	}
	*j = Line(plain)
	return nil
}

type ListRequest struct {
	Op string `json:"op"`
}

func (j *ListRequest) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["op"]; raw != nil && !ok {
		return fmt.Errorf("field op in ListRequest: required")
	}
	type Plain ListRequest
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = ListRequest(plain)
	return nil
}

type ListResponse struct {
	DefaultModel string `json:"default_model"`

	Loading *string `json:"loading,omitempty"`

	Models []ModelSummary `json:"models"`

	Ok bool `json:"ok"`

	Resident interface{} `json:"resident,omitempty"`
}

func (j *ListResponse) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["default_model"]; raw != nil && !ok {
		return fmt.Errorf("field default_model in ListResponse: required")
	}
	if _, ok := raw["models"]; raw != nil && !ok {
		return fmt.Errorf("field models in ListResponse: required")
	}
	if _, ok := raw["ok"]; raw != nil && !ok {
		return fmt.Errorf("field ok in ListResponse: required")
	}
	type Plain ListResponse
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = ListResponse(plain)
	return nil
}

// id is canonical; model is accepted as an alias and is the only op where that
// field is meaningful.
type LoadRequest struct {
	Id *string `json:"id,omitempty"`

	Model *string `json:"model,omitempty"`

	Op string `json:"op"`
}

func (j *LoadRequest) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["op"]; raw != nil && !ok {
		return fmt.Errorf("field op in LoadRequest: required")
	}
	type Plain LoadRequest
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = LoadRequest(plain)
	return nil
}

type LoadResponse struct {
	AlreadyResident bool `json:"already_resident"`

	Engine string `json:"engine"`

	Id string `json:"id"`

	LoadMs float64 `json:"load_ms"`

	Ok bool `json:"ok"`

	// What this load evicted. Always present.
	Unloaded *string `json:"unloaded"`
}

func (j *LoadResponse) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["already_resident"]; raw != nil && !ok {
		return fmt.Errorf("field already_resident in LoadResponse: required")
	}
	if _, ok := raw["engine"]; raw != nil && !ok {
		return fmt.Errorf("field engine in LoadResponse: required")
	}
	if _, ok := raw["id"]; raw != nil && !ok {
		return fmt.Errorf("field id in LoadResponse: required")
	}
	if _, ok := raw["load_ms"]; raw != nil && !ok {
		return fmt.Errorf("field load_ms in LoadResponse: required")
	}
	if _, ok := raw["ok"]; raw != nil && !ok {
		return fmt.Errorf("field ok in LoadResponse: required")
	}
	if _, ok := raw["unloaded"]; raw != nil && !ok {
		return fmt.Errorf("field unloaded in LoadResponse: required")
	}
	type Plain LoadResponse
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = LoadResponse(plain)
	return nil
}

type ModelSummary struct {
	Bytes int `json:"bytes"`

	Description string `json:"description"`

	Engine string `json:"engine"`

	Files int `json:"files"`

	Id string `json:"id"`

	Langs []string `json:"langs"`

	SourceType ModelSummarySourceType `json:"source_type"`

	UnverifiedFiles []string `json:"unverified_files"`
}

type ModelSummarySourceType string

const ModelSummarySourceTypeHuggingface ModelSummarySourceType = "huggingface"
const ModelSummarySourceTypeSystem ModelSummarySourceType = "system"

var enumValues_ModelSummarySourceType = []interface{}{
	"huggingface",
	"system",
}

func (j *ModelSummarySourceType) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_ModelSummarySourceType {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_ModelSummarySourceType, v)
	}
	*j = ModelSummarySourceType(v)
	return nil
}

func (j *ModelSummary) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["bytes"]; raw != nil && !ok {
		return fmt.Errorf("field bytes in ModelSummary: required")
	}
	if _, ok := raw["description"]; raw != nil && !ok {
		return fmt.Errorf("field description in ModelSummary: required")
	}
	if _, ok := raw["engine"]; raw != nil && !ok {
		return fmt.Errorf("field engine in ModelSummary: required")
	}
	if _, ok := raw["files"]; raw != nil && !ok {
		return fmt.Errorf("field files in ModelSummary: required")
	}
	if _, ok := raw["id"]; raw != nil && !ok {
		return fmt.Errorf("field id in ModelSummary: required")
	}
	if _, ok := raw["langs"]; raw != nil && !ok {
		return fmt.Errorf("field langs in ModelSummary: required")
	}
	if _, ok := raw["source_type"]; raw != nil && !ok {
		return fmt.Errorf("field source_type in ModelSummary: required")
	}
	if _, ok := raw["unverified_files"]; raw != nil && !ok {
		return fmt.Errorf("field unverified_files in ModelSummary: required")
	}
	type Plain ModelSummary
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = ModelSummary(plain)
	return nil
}

// One [x, y] corner in source-image pixels.
type Point []float64

type ProbeRequest struct {
	Op ProbeRequestOp `json:"op"`
}

type ProbeRequestOp string

const ProbeRequestOpLivez ProbeRequestOp = "livez"
const ProbeRequestOpReadyz ProbeRequestOp = "readyz"
const ProbeRequestOpStartupz ProbeRequestOp = "startupz"

var enumValues_ProbeRequestOp = []interface{}{
	"livez",
	"readyz",
	"startupz",
}

func (j *ProbeRequestOp) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_ProbeRequestOp {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_ProbeRequestOp, v)
	}
	*j = ProbeRequestOp(v)
	return nil
}

func (j *ProbeRequest) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["op"]; raw != nil && !ok {
		return fmt.Errorf("field op in ProbeRequest: required")
	}
	type Plain ProbeRequest
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = ProbeRequest(plain)
	return nil
}

// resident and loading are present on readyz only.
type ProbeResponse struct {
	Loading *string `json:"loading,omitempty"`

	Ok bool `json:"ok"`

	Probe ProbeResponseProbe `json:"probe"`

	Reasons []string `json:"reasons"`

	Resident interface{} `json:"resident,omitempty"`

	Status ProbeResponseStatus `json:"status"`

	UptimeS float64 `json:"uptime_s"`
}

type ProbeResponseProbe string

const ProbeResponseProbeLivez ProbeResponseProbe = "livez"
const ProbeResponseProbeReadyz ProbeResponseProbe = "readyz"
const ProbeResponseProbeStartupz ProbeResponseProbe = "startupz"

var enumValues_ProbeResponseProbe = []interface{}{
	"livez",
	"readyz",
	"startupz",
}

func (j *ProbeResponseProbe) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_ProbeResponseProbe {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_ProbeResponseProbe, v)
	}
	*j = ProbeResponseProbe(v)
	return nil
}

type ProbeResponseStatus string

const ProbeResponseStatusFail ProbeResponseStatus = "fail"
const ProbeResponseStatusPass ProbeResponseStatus = "pass"

var enumValues_ProbeResponseStatus = []interface{}{
	"pass",
	"fail",
}

func (j *ProbeResponseStatus) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_ProbeResponseStatus {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_ProbeResponseStatus, v)
	}
	*j = ProbeResponseStatus(v)
	return nil
}

func (j *ProbeResponse) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["ok"]; raw != nil && !ok {
		return fmt.Errorf("field ok in ProbeResponse: required")
	}
	if _, ok := raw["probe"]; raw != nil && !ok {
		return fmt.Errorf("field probe in ProbeResponse: required")
	}
	if _, ok := raw["reasons"]; raw != nil && !ok {
		return fmt.Errorf("field reasons in ProbeResponse: required")
	}
	if _, ok := raw["status"]; raw != nil && !ok {
		return fmt.Errorf("field status in ProbeResponse: required")
	}
	if _, ok := raw["uptime_s"]; raw != nil && !ok {
		return fmt.Errorf("field uptime_s in ProbeResponse: required")
	}
	type Plain ProbeResponse
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = ProbeResponse(plain)
	return nil
}

// First datagram of every message. Small and fixed-shape, so it always fits in one
// datagram no matter how large the message is.
type Prologue struct {
	// Bytes of UTF-8 JSON control block that follow.
	ControlLen int `json:"control_len"`

	// Bytes of opaque payload that follow the control block.
	PayloadLen int `json:"payload_len"`

	// Wire version. 2 is dip/2.
	Protocol *int `json:"protocol,omitempty"`
}

func (j *Prologue) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["control_len"]; raw != nil && !ok {
		return fmt.Errorf("field control_len in Prologue: required")
	}
	if _, ok := raw["payload_len"]; raw != nil && !ok {
		return fmt.Errorf("field payload_len in Prologue: required")
	}
	type Plain Prologue
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if 1 > plain.ControlLen {
		return fmt.Errorf("field %s: must be >= %v", "control_len", 1)
	}
	if 0 > plain.PayloadLen {
		return fmt.Errorf("field %s: must be >= %v", "payload_len", 0)
	}
	*j = Prologue(plain)
	return nil
}

// The model that can answer infer right now. Null when nothing is loaded.
type Resident struct {
	Engine string `json:"engine"`

	Id string `json:"id"`

	Langs []string `json:"langs"`

	ResidentSeconds float64 `json:"resident_seconds"`
}

func (j *Resident) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["engine"]; raw != nil && !ok {
		return fmt.Errorf("field engine in Resident: required")
	}
	if _, ok := raw["id"]; raw != nil && !ok {
		return fmt.Errorf("field id in Resident: required")
	}
	if _, ok := raw["langs"]; raw != nil && !ok {
		return fmt.Errorf("field langs in Resident: required")
	}
	if _, ok := raw["resident_seconds"]; raw != nil && !ok {
		return fmt.Errorf("field resident_seconds in Resident: required")
	}
	type Plain Resident
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = Resident(plain)
	return nil
}

type UnloadRequest struct {
	Op string `json:"op"`
}

func (j *UnloadRequest) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["op"]; raw != nil && !ok {
		return fmt.Errorf("field op in UnloadRequest: required")
	}
	type Plain UnloadRequest
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = UnloadRequest(plain)
	return nil
}

type UnloadResponse struct {
	Ok bool `json:"ok"`

	Unloaded *string `json:"unloaded"`
}

func (j *UnloadResponse) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["ok"]; raw != nil && !ok {
		return fmt.Errorf("field ok in UnloadResponse: required")
	}
	if _, ok := raw["unloaded"]; raw != nil && !ok {
		return fmt.Errorf("field unloaded in UnloadResponse: required")
	}
	type Plain UnloadResponse
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = UnloadResponse(plain)
	return nil
}
